require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

# We use `gems.rb` in this project
Bundler/GemFilename:
  EnforcedStyle: gems.rb

# Totally disable this check
# since we don't initialize class directly in spec
# and checking of one class can be split into different specs
RSpec/DescribeClass:
  Enabled: false

# Totally disable this check
# since we use instance variable in spec
RSpec/InstanceVariable:
  Enabled: false
