# frozen_string_literal: true

require_relative 'documents_filter/documents_folder_filter'
require_relative 'documents_filter/documents_img_media_archives_filter'
require_relative 'documents_filter/documents_users_groups_filter'
require_relative 'documents_filter/docx_xlsx_pptx_filter'
require_relative 'documents_account_creation'
require_relative 'documents_actions_button'
require_relative 'documents_favorite_smoke'
require_relative 'documents_file_menu'
require_relative 'documents_group_actions'
require_relative 'documents_recent_smoke'
require_relative 'documents_select_all_checkbox'
