# frozen_string_literal: true

require_relative 'shared_examples/documents_filter/documents_folder_filter'
require_relative 'shared_examples/documents_filter/documents_img_media_archives_filter'
require_relative 'shared_examples/documents_filter/documents_users_groups_filter'
require_relative 'shared_examples/documents_filter/docx_xlsx_pptx_filter'
require_relative 'shared_examples/documents_account_creation'
require_relative 'shared_examples/documents_actions_button'
require_relative 'shared_examples/documents_favorite_smoke'
require_relative 'shared_examples/documents_file_menu'
require_relative 'shared_examples/documents_group_actions'
require_relative 'shared_examples/documents_recent_smoke'
require_relative 'shared_examples/documents_select_all_checkbox'
